### ISSUE TITLE
Cache Kernel sources for e2e tests

### ISSUE THREAD

**Issue by alexellis** [falcosecurity/libs#1848]
**Motivation**

Improve speed of e2e tests, reduce bandwidth usage when downloading Kernel sources for Arm64 jobs that run on actuated.

The resulting cache is ~ 400mb and works out quicker to restore than to do a git clone and checkout.

https://github.com/falcosecurity/libs/blob/master/.github/workflows/e2e_ci.yml#L67

**Feature**

The following does a git clone:

```yaml
      - name: Install kernel headers (actuated)
        uses: self-actuated/get-kernel-sources@master
        if: matrix.arch == 'arm64'
```

I've added instructions to use caching which sped things up about 2x during my own testing.

YMMV, but it's very quick and easy to test out:

See: https://github.com/self-actuated/get-kernel-sources/blob/master/README.md#caching-the-sources

**Alternatives**

Carry on cloning and unpacking sources on every test run.

**Additional context**

I think @LucaGuerra added this originally.
