### ISSUE TITLE
Runtime error: Failing to enrich events with Kubernetes metadata:node name does not correspond to a node in the cluster. Exiting.

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/libs#246]
**Describe the bug**

This [commit](https://github.com/falcosecurity/libs/commit/97dd002dfc81b2df1f41071ca489db1745bc6668) appears to be causing a failure to start falco upon upgrading to v0.31.1.

The only change we made was to increase the version number from 0.31.0 to 0.31.1 in our deployment manifest.

**How to reproduce it**

Deploy Falco as a daemonset in Azure AKS.
This worked in 0.31.0 but fails in 0.31.1.

**Expected behaviour**

Falco should start properly

**Environment**

- Falco version: 0.31.1

- System info:

- Cloud provider or hardware configuration: Azure AKS
- OS: Ubuntu Bionic

- Kernel: 5.8

- Installation method: Kubernetes daemonset

**Additional context**

We are using the downward API to inject the hostname in the pod's environment:
```
        env:
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```

And we do pass `--k8s-node="${FALCO_K8S_NODE_NAME}"` as well which would seem to work. So it seems as if this check is not working for Azure for some reason.

Please let me know what other debugging related output I can provide to help troubleshoot.
