### ISSUE TITLE
k8s.pod.labels not up-to-date after labels are changed on kubernetes

### ISSUE THREAD

**Issue by holyspectral** [falcosecurity/libs#62]
**Describe the bug**
`k8s.pod.labels` is not up-to-date after labels are changed using `kubectl edit`.

**How to reproduce it**

1. Install kernel header on container host.
2. Install falco using official helm.
    ```
    helm install falco -f custom-rules.yaml falcosecurity/falco
    ```
    custom-rules.yaml: (The `labels=%k8s.pod.labels` is added in output field.)
    ```
    ebpf:
      enabled: true

    falco:
      rulesFile:
        - /etc/falco/rules.d
    
    customRules:
      rules-test.yaml: |-
        - macro: always_true
          condition: (evt.num>=0)
        
        - macro: never_true
          condition: (evt.num=0)
        
        - macro: container
          condition: (container.id != host)
        
        - macro: container_entrypoint
          condition: (not proc.pname exists or proc.pname in (runc:[0:PARENT], runc:[1:CHILD], runc, docker-runc, exe, docker-runc-cur))
        
        - list: shell_binaries
          items: [ash, bash, csh, ksh, sh, tcsh, zsh, dash]
        
        - macro: spawned_process
          condition: evt.type = execve and evt.dir=<
        
        - macro: shell_procs
          condition: proc.name in (shell_binaries)
    
        - macro: user_expected_terminal_shell_in_container_conditions
          condition: (never_true)
        
        - rule: Terminal shell in container
          desc: A shell was used as the entrypoint/exec point into a container with an attached terminal.
          condition: >
            spawned_process and container
            and shell_procs and proc.tty != 0
            and container_entrypoint
            and not user_expected_terminal_shell_in_container_conditions
          output: >
            A shell was spawned in a container with an attached terminal (user=%user.name user_loginuid=%user.loginuid %container.info
            shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline terminal=%proc.tty container_id=%container.id image=%container.image.repository labels=%k8s.pod.labels)
          priority: NOTICE
          tags: [container, shell, mitre_execution]

    ```
3. Add a new label to falco pod using `kubectl edit`.
    ```
    labels:
      newlabel: label
    ```
4. Get into falco pod using `kubectl exec -it bash`
5. Check falco logs.  The new label is not present.
    ```
    16:52:42.515386752: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1 k8s.ns=default k8s.pod=falco-szn5s container=e115b9a04a74 shell=bash parent=runc cmdline=bash terminal=34816 container_id=e115b9a04a74 image=falcosecurity/falco labels=app:falco, controller-revision-hash:6db874fd77, pod-template-generation:1, role:security)

    ```

**Expected behaviour**

The new label is present in falco output and can be used in rule condition.

**Screenshots**
![Screenshot from 2021-07-27 12-54-46](https://user-images.githubusercontent.com/11805094/127199757-dbb47b85-0564-4d69-80ca-6f26d2ab0c58.png)

![Screenshot from 2021-07-27 12-55-13](https://user-images.githubusercontent.com/11805094/127195868-aff33bee-1c36-4b1e-ae56-5fcde0a338ea.png)

**Environment**

- Falco version:
  ```
  Falco version: 0.29.1
  Driver version: 17f5df52a7d9ed6bb12d3b1768460def8439936d
  ```

- System info:
  ```
  {
    "machine": "x86_64",
    "nodename": "",
    "release": "5.4.95-42.163.amzn2.x86_64",
    "sysname": "Linux",
    "version": "#1 SMP Thu Feb 4 12:50:05 UTC 2021"
  }
  ```

- Cloud provider or hardware configuration: EKS 1.19 + node v1.19.6-eks-49a6c0
- OS:
  ```
  NAME="Amazon Linux"
  VERSION="2"
  ID="amzn"
  ID_LIKE="centos rhel fedora"
  VERSION_ID="2"
  PRETTY_NAME="Amazon Linux 2"
  ANSI_COLOR="0;33"
  CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
  HOME_URL="https://amazonlinux.com/"
  ```

- Kernel: 5.4.95-42.163.amzn2.x86_64

- Installation method: Kubernetes

**Additional context**

The issue can be reproduced with `0.29.0` but not with `0.28.1`.
The output with `0.28.1`:
![Screenshot from 2021-07-27 13-12-53](https://user-images.githubusercontent.com/11805094/127199689-b432d4ee-25fd-4175-8056-d9e16538f6c4.png)
Potentially related to https://github.com/falcosecurity/libs/pull/15 as no API is available in [CRI](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto) to update `io.kubernetes.sandbox.id` label.
